# Generated by Django 5.2.9 on 2025-12-06 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gifts',
            name='price',
        ),
    ]
