# Generated by Django 5.2.9 on 2025-12-06 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_remove_gifts_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gifts',
            name='order_number',
            field=models.IntegerField(),
        ),
    ]
