# Generated by Django 5.2.9 on 2025-12-06 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_alter_gifts_order_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='qrcode',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='qrcode',
            name='token',
            field=models.CharField(blank=True, max_length=64, unique=True),
        ),
    ]
