# Generated by Django 5.2.9 on 2025-12-08 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_qrcode_created_at_qrcode_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_viewed',
            field=models.BooleanField(default=False),
        ),
    ]
