# Generated by Django 5.2.9 on 2026-06-15 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_order_is_viewed'),
    ]

    operations = [
        migrations.DeleteModel(
            name='QRCode',
        ),
        migrations.RemoveField(
            model_name='gifts',
            name='available',
        ),
        migrations.RemoveField(
            model_name='gifts',
            name='order_number',
        ),
        migrations.RemoveField(
            model_name='order',
            name='customer_name',
        ),
        migrations.RemoveField(
            model_name='order',
            name='customer_phone',
        ),
        migrations.AddField(
            model_name='gifts',
            name='count',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='gifts',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='order',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
    ]
