server {
    listen 80;
    server_name mariyam-new-year.uz www.mariyam-new-year.uz;

    client_max_body_size 20M;

    location /static/ {
        alias /home/mariyam-new-year/staticfiles/;
        expires 30d;
        add_header Cache-Control "public, immutable";
    }

    location /media/ {
        alias /home/mariyam-new-year/media/;
        expires 7d;
        add_header Cache-Control "public";
    }

    location / {
        include proxy_params;
        proxy_pass http://unix:/run/mariyam-new-year.sock;
        proxy_read_timeout 120;
        proxy_connect_timeout 120;
        proxy_redirect off;
    }
}
